### ISSUE TITLE
Add screenshots to the README

### ISSUE THREAD

**Issue by vijay-jaisankar** [vijay-jaisankar/pandemonium#11]
PR Activity ref: #8 

Links to get started:
- https://www.educative.io/answers/adding-images-to-readmemd-in-github

**Comment by yr1404** [comment]
I am working on it.

**Comment by vijay-jaisankar** [comment]
Sure, for your next contributions, please comment your intent to take it up like you did in #16.

**Comment by yr1404** [comment]
Please look if there is any changes required.
