### ISSUE TITLE
Add a favicon to the website

### ISSUE THREAD

**Issue by vijay-jaisankar** [vijay-jaisankar/pandemonium#16]
PR Activity ref: #8 

Links to get started
- https://flask.palletsprojects.com/en/2.3.x/patterns/favicon/

**Comment by yr1404** [comment]
Do you want a meme favicon or some illustration/designs?

**Comment by vijay-jaisankar** [comment]
@yr1404 Anything that you think fits well with the theme of the project! Ideally some sort of illustration that conveys the theme would be great

**Comment by yr1404** [comment]
I would suggest this one :
![favicon](https://github.com/vijay-jaisankar/pandemonium/assets/106465753/3f8fd92e-a39c-47f7-9e63-9e75735d501e)

**Comment by vijay-jaisankar** [comment]
Looks awesome!
