### ISSUE TITLE
Add more meta tags to the HTML page

### ISSUE THREAD

**Issue by vijay-jaisankar** [vijay-jaisankar/pandemonium#17]
PR Activity ref: #8 

Links to get started
- https://www.searchenginejournal.com/important-tags-seo/156440/

**Comment by ATiwari2000** [comment]
Hi, if you can clarify more about what tags you want, I would like to work on this,
Thanks

**Comment by vijay-jaisankar** [comment]
Hi @ATiwari2000 , thanks for taking this up!

A good place to start would be this checklist: Accessibility Checklist - Minnesota Department of Health https://www.health.state.mn.us/about/tools/allychecklist.pdf

**Comment by vijay-jaisankar** [comment]
closed via https://github.com/vijay-jaisankar/pandemonium/pull/23
