### ISSUE TITLE
Flask tests

### ISSUE THREAD

**Issue by vijay-jaisankar** [vijay-jaisankar/pandemonium#19]
PR Activity ref: #8 

Links to get started
- https://flask.palletsprojects.com/en/2.3.x/testing/

**Comment by mimeosd** [comment]
Why did you use `global` keyword in index() ? You are not modifying it or anyting so I see no need to include it. Just a small suggestion.

**Comment by vijay-jaisankar** [comment]
Hi @mimeosd - that's a great observation, thanks! Indeed, as we aren't modifying the variable, the `global` moniker is vestigial. Feel free to make a PR addressing this if you'd like :)

**Comment by vijay-jaisankar** [comment]
addressed in https://github.com/vijay-jaisankar/pandemonium/pull/23
